### ISSUE TITLE
Panic when opening Glyph

### ISSUE THREAD

**Issue by alerque** [linebender/runebender#218]
Try to test the new pan functionality, using 1c880f4...

Opening a UFO file works fine. If If double click on a glyph, it panics:

```console
$ RUST_BACKTRACE=1 cargo run -- ~/projects/github/baby-shark/sources/BabyShark-Regular.ufo
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/runebender /home/caleb/projects/github/baby-shark/sources/BabyShark-Regular.ufo`
DEBUG [druid::localization] available locales [], current en-US
DEBUG [druid::localization] resolved: [en-US]
TRACE [mio::poll] registering with poller
TRACE [mio::poll] registering with poller
TRACE [mio::poll] registering with poller
INFO  [druid_theme_loader::widget] loaded 45 items to theme
INFO  [druid_shell::platform::gtk::application] gtk: Activated application
thread 'main' panicked at 'assertion failed: mid <= self.len()', /home/caleb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs:2523:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
   3: core::slice::<impl [T]>::rotate_left
             at /home/caleb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs:2523:9
   4: runebender_lib::cubic_path::CubicPath::from_norad
             at ./runebender-lib/src/cubic_path.rs:140:13
   5: runebender_lib::path::Path::from_norad
             at ./runebender-lib/src/path.rs:42:13
   6: core::ops::function::FnMut::call_mut
             at /home/caleb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:150:5
   7: core::iter::adapters::map_fold::{{closure}}
             at /home/caleb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:905:28
   8: core::iter::traits::iterator::Iterator::fold
             at /home/caleb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2023:21
   9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /home/caleb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:945:9
  10: core::iter::traits::iterator::Iterator::for_each
             at /home/caleb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:678:9
  11: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /home/caleb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2335:17
  12: <alloc::vec::Vec<T> as alloc::vec::SpecFromIterNested<T,I>>::from_iter
             at /home/caleb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2109:9
  13: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
             at /home/caleb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2119:9
  14: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /home/caleb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:1959:9
  15: core::iter::traits::iterator::Iterator::collect
             at /home/caleb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1670:9
  16: runebender_lib::edit_session::EditSession::new::{{closure}}
             at ./runebender-lib/src/edit_session.rs:76:23
  17: core::option::Option<T>::map
             at /home/caleb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:453:29
  18: runebender_lib::edit_session::EditSession::new
             at ./runebender-lib/src/edit_session.rs:73:32
  19: runebender_lib::data::Workspace::get_or_create_session::{{closure}}
             at ./runebender-lib/src/data.rs:182:40
  20: core::option::Option<T>::unwrap_or_else
             at /home/caleb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:427:21
  21: runebender_lib::data::Workspace::get_or_create_session
             at ./runebender-lib/src/data.rs:177:9
  22: <runebender_lib::app_delegate::Delegate as druid::app_delegate::AppDelegate<runebender_lib::data::AppState>>::command
             at ./runebender-lib/src/app_delegate.rs:70:35
  23: druid::win_handler::Inner<T>::delegate_cmd::{{closure}}
             at /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid/src/win_handler.rs:226:50
  24: druid::win_handler::Inner<T>::with_delegate
             at /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid/src/win_handler.rs:210:18
  25: druid::win_handler::Inner<T>::delegate_cmd
             at /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid/src/win_handler.rs:226:9
  26: druid::win_handler::Inner<T>::dispatch_cmd
             at /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid/src/win_handler.rs:338:23
  27: druid::win_handler::AppState<T>::handle_cmd
             at /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid/src/win_handler.rs:644:17
  28: druid::win_handler::AppState<T>::process_commands
             at /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid/src/win_handler.rs:568:30
  29: druid::win_handler::AppState<T>::do_window_event
             at /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid/src/win_handler.rs:536:9
  30: <druid::win_handler::DruidHandler<T> as druid_shell::window::WinHandler>::mouse_down
             at /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid/src/win_handler.rs:863:9
  31: druid_shell::platform::gtk::window::WindowBuilder::build::{{closure}}::{{closure}}
             at /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid-shell/src/platform/gtk/window.rs:431:29
  32: druid_shell::platform::gtk::window::WindowState::with_handler_and_dont_check_the_other_borrows
             at /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid-shell/src/platform/gtk/window.rs:685:31
  33: druid_shell::platform::gtk::window::WindowState::with_handler
             at /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid-shell/src/platform/gtk/window.rs:673:19
  34: druid_shell::platform::gtk::window::WindowBuilder::build::{{closure}}
             at /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid-shell/src/platform/gtk/window.rs:413:17
  35: <O as gtk::auto::widget::WidgetExt>::connect_button_press_event::button_press_event_trampoline
             at /home/caleb/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.9.2/src/auto/widget.rs:3060:13
  36: <unknown>
  37: g_closure_invoke
  38: <unknown>
  39: g_signal_emit_valist
  40: g_signal_emit
  41: <unknown>
  42: <unknown>
  43: gtk_main_do_event
  44: <unknown>
  45: <unknown>
  46: g_main_context_dispatch
  47: <unknown>
  48: g_main_context_iteration
  49: g_application_run
  50: <O as gio::application::ApplicationExtManual>::run
             at /home/caleb/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.9.1/src/application.rs:23:13
  51: druid_shell::platform::gtk::application::Application::run
             at /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid-shell/src/platform/gtk/application.rs:65:9
  52: druid_shell::application::Application::run
             at /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid-shell/src/application.rs:153:9
  53: druid::app::AppLauncher<T>::launch
             at /home/caleb/.cargo/git/checkouts/druid-f71533f3d81c0bc8/fb434a1/druid/src/app.rs:183:9
  54: runebender::main
             at ./src/main.rs:19:5
  55: core::ops::function::FnOnce::call_once
             at /home/caleb/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by cmyr** [comment]
Yes I hit this too, was a bug in #216. This is fixed in 24c9a64.
